### ISSUE TITLE
SDP to dot conversion crash

### ISSUE THREAD

**Issue by namednil** [cfmrp/mtool#71]
mtool crashes on [s.txt](https://github.com/cfmrp/mtool/files/4198959/s.txt) with the command
```
python mtool/main.py --id 22100001 --read dm --write dot s.txt o.dot

Traceback (most recent call last):
  File "mtool/main.py", line 397, in <module>
    main();
  File "mtool/main.py", line 379, in main
    ids = arguments.ids, strings = arguments.strings);
  File "/tmp/mtool_stuff/mtool/graph.py", line 735, in dot
    node.dot(stream, self.input, ids, strings, errors);
  File "/tmp/mtool_stuff/mtool/graph.py", line 216, in dot
    anchor["from"], anchor["to"]),
TypeError: string indices must be integers
```
The input should be well-formed (?) but mtool also complains with `--validate all` that
```
validate(): [E] graph #22100001: missing or invalid ‘input’ property.
```

I also noticed that it is very sensitive to the number of new lines at the end of the file. It seems to ignore the last graph in the file if there are fewer than two new line symbols.

**Comment by danielhers** [comment]
@oepen is the `input` validation necessary? When reading SDP files, it's not available.

**Comment by oepen** [comment]
i see that daniel has made the code more robust already, but there is a deeper question lurking here: arguably, a well-formed DM graph (in the modern MRP universe) requires both the `input` field and (consecutive, non-overlapping) anchoring on all nodes into that string.  in this regard, the MRP interpretation of the DM (and other bi-lexical graphs) is more stringent than the original SDP data format (where parser inputs in fact were pre-tokenized and tagged sequences, much like in early work on data-driven syntactic dependency parsing).

in practise, that means that conversion from DM to MRP should require the missing information, i.e. make the additional `--text` argument obligatory.  i will be tempted to implement that requirement (unless i hear objections) soon.

regarding the 'missing' final graph, the SDP file format (much like earlier newline- and tab-separated CoNLL conventions) does require the double-newline termination of the file, so arguably the code was doing the right thing but probably should have flagged the input file as semi-illformed, i.e. generate a warning about 'junk' following the last complete graph.

more on the content side, it appears you may be wanting to evaluate on the original SDP gold-standard test data, which of course is reasonably close (but not identical) to the MRP 2019 DM test data?  we have in the meantime decided that we shall share the complete 2019 evaluation data with all participants, but will have to channel that through the LDC (which i have been meaning to initiate for several weeks now).  so, please stay tuned for an announcement of access to the MRP evaluation data relatively soon, i hope :-).

**Comment by danielhers** [comment]
Thanks @oepen. I think the requirement you mentioned makes sense. In a [branch](https://github.com/cfmrp/mtool/tree/input-validation) I removed the `input` validation for SDP-formatted inputs but following your comment I assume we will just discard that branch and not merge it.

**Comment by namednil** [comment]
@oepen I do see your point but being able to visualize old SDP files with mtool would be quite useful. Perhaps, the `--text` argument should be obligatory except if the graphs are read and converted to dot notation?

I was not trying to get evaluation results on the test data (I just noticed the problem and these were the first gold graphs at hand) but that's good to know, thanks!

**Comment by danielhers** [comment]
Or we could just leave the situation as it is, and allow processing SDP file without `input`/`--text`, while informing the user that they are invalid when they run `--validate all` (perhaps with a more informative message about how to resolve the problem).
